<?php
namespace Yellowstep\ElementorEditor\Rest;
use WP_Error; use WP_REST_Request; use Yellowstep\ElementorEditor\Core; use Yellowstep\ElementorEditor\Elementor\DataStore; use Yellowstep\ElementorEditor\Elementor\Walker; use Yellowstep\ElementorEditor\Editor\PageEditor; use Yellowstep\ElementorEditor\Semantic\PageMap; use Yellowstep\ElementorEditor\SEO\Yoast; use Yellowstep\ElementorEditor\Safety\Snapshots;
if (!defined('ABSPATH')) { exit; }
final class Routes {
    public static function register(): void {
        $routes=[['GET','/pages',[self::class,'pages']],['GET','/templates',[self::class,'templates']],['GET','/structure/(?P<id>\\d+)',[self::class,'structure']],['GET','/semantic-map/(?P<id>\\d+)',[self::class,'semanticMap']],['GET','/snapshots/(?P<id>\\d+)',[self::class,'snapshots']],['POST','/duplicate-page',[self::class,'duplicatePage']],['POST','/create-service-page',[self::class,'createServicePage']],['POST','/update-section-field',[self::class,'updateSectionField']],['POST','/update-card',[self::class,'updateCard']],['POST','/update-faq',[self::class,'updateFaq']],['POST','/replace-text',[self::class,'replaceText']],['POST','/update-yoast',[self::class,'updateYoast']],['POST','/rollback',[self::class,'rollback']],['POST','/regenerate-css',[self::class,'regenerateCss']]];
        foreach($routes as $route){register_rest_route(Core::REST_NAMESPACE,$route[1],['methods'=>$route[0],'callback'=>$route[2],'permission_callback'=>[Core::class,'canEditPages']]);}
    }
    public static function pages(WP_REST_Request $r){return rest_ensure_response(['items'=>Core::listElementorPages()]);}
    public static function templates(WP_REST_Request $r){return rest_ensure_response(['items'=>Core::listTemplates()]);}
    public static function structure(WP_REST_Request $r){$postId=intval($r['id']);$post=Core::postCheck($postId);if(is_wp_error($post))return $post;$items=Walker::structure($postId);return rest_ensure_response(['post_id'=>$postId,'title'=>Core::cleanTitle($post),'link'=>get_permalink($postId),'widget_count'=>count($items),'items'=>$items]);}
    public static function semanticMap(WP_REST_Request $r){$postId=intval($r['id']);$post=Core::postCheck($postId);if(is_wp_error($post))return $post;return rest_ensure_response(['post_id'=>$postId,'title'=>Core::cleanTitle($post),'map'=>PageMap::build($postId)]);}
    public static function duplicatePage(WP_REST_Request $r){$result=PageEditor::duplicatePage(intval($r->get_param('post_id')),sanitize_text_field($r->get_param('title')?:''),sanitize_title($r->get_param('slug')?:''),sanitize_key($r->get_param('status')?:'draft'));return is_wp_error($result)?$result:rest_ensure_response($result);}
    public static function createServicePage(WP_REST_Request $r){$title=sanitize_text_field($r->get_param('title')); if(!$title)return new WP_Error('invalid','title is required.',['status'=>400]); $result=PageEditor::duplicatePage(intval($r->get_param('source_id')),$title,sanitize_title($r->get_param('slug')?:$title),sanitize_key($r->get_param('status')?:'draft')); if(is_wp_error($result))return $result; if($r->get_param('seo_title')||$r->get_param('meta_description')||$r->get_param('focus_keyphrase')) Yoast::update($result['new_id'],$r->get_param('seo_title'),$r->get_param('meta_description'),$r->get_param('focus_keyphrase')); return rest_ensure_response($result);}
    public static function updateSectionField(WP_REST_Request $r){$postId=intval($r->get_param('post_id'));$post=Core::postCheck($postId);if(is_wp_error($post))return $post;$result=PageEditor::updateSectionField($postId,sanitize_key($r->get_param('section')),sanitize_key($r->get_param('field')),(string)$r->get_param('value'));return is_wp_error($result)?$result:rest_ensure_response($result);}
    public static function updateCard(WP_REST_Request $r){$postId=intval($r->get_param('post_id'));$post=Core::postCheck($postId);if(is_wp_error($post))return $post;$result=PageEditor::updateCard($postId,intval($r->get_param('index')),$r->get_param('title'),$r->get_param('description'));return is_wp_error($result)?$result:rest_ensure_response($result);}
    public static function updateFaq(WP_REST_Request $r){$postId=intval($r->get_param('post_id'));$post=Core::postCheck($postId);if(is_wp_error($post))return $post;$result=PageEditor::updateFaq($postId,intval($r->get_param('index')),$r->get_param('question'),$r->get_param('answer'));return is_wp_error($result)?$result:rest_ensure_response($result);}
    public static function replaceText(WP_REST_Request $r){$postId=intval($r->get_param('post_id'));$post=Core::postCheck($postId);if(is_wp_error($post))return $post;$result=PageEditor::replaceText($postId,(string)$r->get_param('old_text'),(string)$r->get_param('new_text'));return is_wp_error($result)?$result:rest_ensure_response($result);}
    public static function updateYoast(WP_REST_Request $r){$postId=intval($r->get_param('post_id'));$post=Core::postCheck($postId);if(is_wp_error($post))return $post;return rest_ensure_response(Yoast::update($postId,$r->get_param('seo_title'),$r->get_param('meta_description'),$r->get_param('focus_keyphrase')));}
    public static function snapshots(WP_REST_Request $r){$postId=intval($r['id']);$post=Core::postCheck($postId);if(is_wp_error($post))return $post;return rest_ensure_response(['post_id'=>$postId,'snapshots'=>Snapshots::all($postId)]);}
    public static function rollback(WP_REST_Request $r){$postId=intval($r->get_param('post_id'));$post=Core::postCheck($postId);if(is_wp_error($post))return $post;$index=$r->get_param('index');$result=Snapshots::rollback($postId,$index===null?null:intval($index));return is_wp_error($result)?$result:rest_ensure_response($result);}
    public static function regenerateCss(WP_REST_Request $r){$postId=intval($r->get_param('post_id')?:0);DataStore::clearCache($postId);return rest_ensure_response(['regenerated'=>true,'post_id'=>$postId]);}
}
